name: build-openwrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - aarch64_generic
          - mips_24kc
          - x86_64
        branch:
          - SNAPSHOT
          - openwrt-25.12
          - openwrt-24.10

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: checkout-action
        uses: actions/checkout@v6
        with:
          repository: openwrt/gh-action-sdk
          ref: main
          path: .gh-action-sdk

      - name: patch-action
        run: |
          sed -i \
            's|"package/$PKG/check" V=s|"package/$PKG/check" V=s FIXUP=1|' \
            .gh-action-sdk/entrypoint.sh

      - name: build
        uses: ./.gh-action-sdk
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          PACKAGES: asterisk-chan-quectel
          NO_REFRESH_CHECK: true
          V: s
          FIXUP: 1

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: chan-quectel-${{ matrix.arch }}-${{ matrix.branch }}
          path: |
            bin/packages/${{ matrix.arch }}/action/asterisk-chan-quectel*.[ai]pk
          if-no-files-found: error
